title: Francasalf Hub
description: Repositorio personal con materiales y referencias en formato Markdown.
author: Fran Casal
lang: es-ES

url: "https://francasalf-hub.github.io"
baseurl: ""  # sitio en la raíz

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Enlaces útiles
social_links:
  - name: Edu.xunta.gal
    url: https://www.edu.xunta.gal/
  - name: Diario Oficial de Galicia (DOG)
    url: https://www.xunta.gal/diario-oficial-galicia
  - name: BOE
    url: https://www.boe.es/
  - name: Lex.gal
    url: https://www.lex.gal/

# Plugins requeridos por GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Tema del sitio
theme: jekyll-theme-cayman
