title: Francasalf Hub
description: Repositorio personal con materiales y referencias en formato Markdown.
author: Fran Casal
lang: es-ES

url: "https://francasalf-hub.github.io"
baseurl: ""  # sitio en la ra√≠z

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins requeridos por GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Tema del sitio
theme: jekyll-theme-cayman
